// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reservsoft.DATA;

#nullable disable

namespace reservsoft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApartamentosReservas", b =>
                {
                    b.Property<int>("ApartamentosIdApartamento")
                        .HasColumnType("int");

                    b.Property<int>("ReservaNumReserva")
                        .HasColumnType("int");

                    b.HasKey("ApartamentosIdApartamento", "ReservaNumReserva");

                    b.HasIndex("ReservaNumReserva");

                    b.ToTable("ReservasApartamentos", (string)null);
                });

            modelBuilder.Entity("reservsoft.Models.Apartamentos", b =>
                {
                    b.Property<int>("IdApartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApartamento"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("Tamaño")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<string>("TipoApartamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdApartamento");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("reservsoft.Models.Descuento", b =>
                {
                    b.Property<int>("IdDescuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Descuentos")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdApartamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDescuento");

                    b.HasIndex("IdApartamento");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("reservsoft.Models.Mobiliario", b =>
                {
                    b.Property<int>("IdMobiliario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMobiliario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdApartamento")
                        .HasColumnType("int");

                    b.Property<string>("IdentMobiliario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdMobiliario");

                    b.HasIndex("IdApartamento");

                    b.HasIndex("IdentMobiliario")
                        .IsUnique()
                        .HasDatabaseName("IX_IdentMobiliario_Unique");

                    b.ToTable("Mobiliarios");
                });

            modelBuilder.Entity("reservsoft.Models.Reservas", b =>
                {
                    b.Property<int>("NumReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumReserva"));

                    b.Property<int>("Acompanantes")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double>("TotalReserva")
                        .HasColumnType("float");

                    b.HasKey("NumReserva");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("reservsoft.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApartamentosReservas", b =>
                {
                    b.HasOne("reservsoft.Models.Apartamentos", null)
                        .WithMany()
                        .HasForeignKey("ApartamentosIdApartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reservsoft.Models.Reservas", null)
                        .WithMany()
                        .HasForeignKey("ReservaNumReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("reservsoft.Models.Descuento", b =>
                {
                    b.HasOne("reservsoft.Models.Apartamentos", null)
                        .WithMany()
                        .HasForeignKey("IdApartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("reservsoft.Models.Mobiliario", b =>
                {
                    b.HasOne("reservsoft.Models.Apartamentos", null)
                        .WithMany()
                        .HasForeignKey("IdApartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
